#GET https://restful-booker.herokuapp.com/booking


POST https://restful-booker.herokuapp.com/booking

  Content-Type: application/json

  {
    "firstname" : "Jim",
    "lastname" : "Brown",
    "totalprice" : 111,
    "depositpaid" : true,
    "bookingdates" : {
        "checkin" : "2027-01-01",
        "checkout" : "2027-01-11"
    },
    "additionalneeds" : "Breakfast"
}